### ISSUE TITLE
Linux installation script not working right

### ISSUE THREAD

**Issue by levkk** [danvergara/dblab#208]
**Describe the bug**
The Linux installation script installs the binary into `~/.local/bin`, i.e. it makes that path the executable, not a folder, and doesn't copy the executable into it.

**To Reproduce**
Steps to reproduce the behavior: Use the installation script with no arguments.

**Expected behavior**
Should probably install it into `~/.local/bin/dblab` although I don't think that's typically included into `PATH`. Might prompt for password and install into `/usr/local/bin/dblab` instead.

**OS (please complete the following information):**
 -  Arch

**Comment by danvergara** [comment]
I can't reproduce the problem. I've been running this script on Mac, Fedora, Debian and Ubuntu for years and I had no problem at all.

I realized that the [original script](https://github.com/jesseduffield/lazydocker/blob/master/scripts/install_update_linux.sh) I took inspiration from  was improved over the years, tho. I hope it addresses the installation issue.

I won't change the default value because current path is OK as it is and can changed by the user anytime, and won't change it to an administrator directory, either.
