### ISSUE TITLE
Is it possible to support SQLite

### ISSUE THREAD

**Issue by israteneda** [danvergara/dblab#49]
**Is your feature request related to a problem? Please describe.**
It's not related to a specific problem, just I'm wondering if is it possible to use `dblab` with `SQLite`

**Describe the solution you'd like**
I think could be possible support SQLite, but I'm not sure

**Describe alternatives you've considered**
I tried to use `dblab` with `postgres`, but I'd like to just play around with `dblab` and a lightweight database as `SQLite`

**Additional context**
Maybe as SQLite is also an SQL database, it might be possible to support SQLite

**Comment by danvergara** [comment]
That's a good point, but I avoided intentionally because I'm not a SQLite user. As far as I remember, adding SQLite shouldn't be that hard, I think the code is extensible enough to add more driver easily. If you need a walkthrough to show you the places where you'd need to add the required extensions, just let me know. I'd be more than happy to help.

**Comment by israteneda** [comment]
I was trying to integrate the `seeds` with `sqlite` but [golang-migrate/migrate](https://github.com/golang-migrate/migrate) has some issues with `sqlite`, so I think in the next release of `migrate` package we will be able to integrate the `sqlite` seeds
