### ISSUE TITLE
Error when viewing table structure

### ISSUE THREAD

**Issue by nathanaelcunningham** [danvergara/dblab#64]
**Describe the bug**
When pressing 'Enter' on a table, dblab crashes saying 'unknown column 'tc.enforced' in field list

**To Reproduce**
1. Load a database
2. Go to a table and press enter

**Expected behavior**
Should so table structure

**OS (please complete the following information):**
Arch linux

**Additional context**
This is when connecting to a mariaDB database

**Comment by danvergara** [comment]
Thanks for bringing this to my attention. I'll be releasing new stuff these days. I'll be addressing this with a high priority.

**Comment by danvergara** [comment]
I found the problem. Looks like the `enforced`  column is not present in the `information_schema.table_constraints` view in mariadb systems. I can't call this a bug because the client is explicitly built for MySQL and PostgreSQL, since both support this column. But, this is a good insight about what is people using dblab for. 
I can't drop the support for that column in the next release.
